### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by JacobBndct** [JacobBndct/Hooked#1]
Showing all items physically in the shop
![Image](https://github.com/user-attachments/assets/ca177182-c07a-4977-83b1-a2e5ee4e2cdf)

Point and click mechanics to buy
![Image](https://github.com/user-attachments/assets/cc123f64-777f-4a27-9988-ed828f3ba0fe)

**Comment by marssemenova** [comment]
Place pet fish fishbowl and new slot machine (need to port over from dev somehow) @TristanJDuke
